export const Theme = {
  colors: {
    primaryColor: "#fcc125",
    primary: "#fcc125",
    primaryColorDark: "#ffac41",
    textColor: "#323232",
    black: "#000000",
    sec: "#0063FF",
    gray: "gray",
    lightgray: "lightgray",
    green: "#2db074",
    yellow: "#fcc125",
    yellowDark: "#edac00",
    windowBackground: "#f9fbfc",
    navbarActiveColor: "#ffac41",
    navbarInactiveColor: "lightgray",
    touchableHighlightUnderlayColor: "#f0f0f0",
    white: "#fff",
  },
  sizes: {
    boxBorderRadius: 12,
    inputHeight: 50,
    separatorSize: 12,
  },
};
